baseURL = "https://drs.is/"
languageCode = "en-us"
title = "Sinistersnare's Blog"
author = "Davis Silverman"
theme = "blackburn"
copyright = "&copy; 2017. All rights reserved."
canonifyurls = true
paginate = 5


[indexes]
   topic = "topics"

[params]
   subtitle = "Coder / Gamer / More Coder"
   brand = "Sin's Blog!"
   dateFormat = "02 Jan 2006"
   # googleAnalytics = "google analytics tracking ID"
   highlightjs = "atelier-seaside-dark" # maybe androidstudio is the best ?
   highlightjs_extra_languages = ["yaml"] # hmm?

[menu] # side menu
[[menu.main]]
   name = "Home"
   pre = "<i class='fa fa-home fa-fw'></i>"
   weight = 1
   identifier = "home"
   url = "/"
[[menu.main]]
   name = "Posts"
   pre = "<i class='fa fa-list fa-fw'></i>"
   weight = 2
   identifier = "post"
   url = "/post/"
[[menu.main]]
   name = "Topics"
   pre = "<i class='fa fa-folder fa-fw'></i>"
   weight = 3
   identifier = "topic"
   url = "/topics/"
[[menu.main]]
   name = "About"
   pre = "<i class='fa fa-user fa-fw'></i>"
   weight = 4
   identifier = "about"
   url = "/about/"
[[menu.main]]
   name = "Contact"
   pre = "<i class='fa fa-phone fa-fw'></i>"
   weight = 5
   identifier = "contact"
   url = "/contact/"

[social]
   twitter = "sinistersnare"
   github = "sinistersnare"


