base_url = "https://thedav.is"

theme = "cork-board"
compile_sass = true
build_search_index = false
generate_feeds = true

taxonomies = [{ name = "tags", rss = true }]
title = "Davis"

ignored_content = ["inversion.xml", "threaded.xml"]

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
katex_enable = true
date_format = "%b %d, %Y"
show_reading_time = true
show_word_count = false
description = "The homepage of the Davis"

menu = [
    { text = "yap", link = "/post" },
    { text = "now", link = "/about" },
    { text = "code", link = "/code" },
]
