# The URL the site will be built for
base_url = "https://drs.is"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Generates atom.xml
generate_feed = true

taxonomies = [
    { name = "tags" , rss = true },
]
title = "Sin's Blog"

theme = "sam"

ignored_content = ["inversion.xml", "threaded.xml"]

[markdown]

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme ="dracula"

[extra]

# Moderately-pilfered from the Even Theme
katex_enable = true

# Sam Config
sam_menu = [
    { text = "Posts", link = "/post" },
    { text = "About", link = "/about" },
    { text = "Works", link = "/work" },
    { text = "GitHub↪", link = "https://github.com/sinistersnare" }
]
sam_bottom_menu = true
home = "Home" # Name for home page links.
date_format = "%b %d, %Y"
show_reading_time = true
show_word_count = false

[extra.sam_footer]
text = "©2017-2021 Davis Silverman"
