baseURL = "https://drs.is"
title = "Sinistersnare's Blog"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minima"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Coder / Gamer / Something Witty-er"
title404 = "Nothing's here! 404, could not find selected resource! Please contact me!"

[params.assets]
favicon = "img/favicon.ico"
customCSS = [] # ["css/custom.css"]
customJS = [] # ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Davis Silverman"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "Jan 02, 2006"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
recentPostsLength = 4
homepageSections = ["recent_posts"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "sinistersnare" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
#codepen = "MunifTanjim"
email = "sinistersnare@gmail.com"
# facebook = "MunifTanjim"
github = "Sinistersnare"
# instagram = "MunifTanjim"
# linkedin = "muniftanjim"
twitter = "Sinistersnare"
# telegram = "MunifTanjim"

[params.social.config]
# platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin","telegram"]
platforms = ["github", "twitter", "email"]

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Home"
weight = 1
url = "/"

[[menu.main]]
name = "About"
weight = 2
url = "/about"

[[menu.main]]
name = "Contact"
weight = 3
url = "/contact"

[[menu.main]]
name = "Projects"
weight = 4
url = "/projects"


[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
