name = "clean"
description = "Davis's Theme"
license = "None"
homepage = "https://github.com/sinistersnare/sinistersnare.github.io"
min_version = "0.4.0"
demo = "https://thedav.is"

[extra]
show_word_count = true
show_reading_time = true

date_format = "%a %b %e, %Y"

home = "home"

sam_bottom_menu = true

[author]
name = "Davis"
homepage = "thedav.is"

[original]
author =  "Victoria"
homepage = "https://hugo-sam.netlify.com"
repo = "https://github.com/victoriadotdev/hugo-theme-sam"
